spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/avia_bot
    username: postgres
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
