package uz.pdp.telegramwebhookapi.Entity.enums;

public enum State {
    ADM_MAIN_STATE,
    ADM_PLANE_STATE,
    ADM_PLANE_ADD_STATE,
    ADM_PLANE_SHOW_STATE,
    ADM_PLANE_DELETE_STATE,
    ADM_PLANE_EDITE_STATE,
    ADM_AERDROM_STATE,
    ADM_AERODROM_ADD_STATE,
    ADM_AERODROM_SHOW_STATE,
    ADM_AERODROM_DELETE_STATE,
    ADM_AERODROM_EDITE_STATE,
    EXTRA_AERO_NAME_STATE,
    EXTRA_AERO_EDIT_ALL,
    EXTRA_PLANE_EDIT_ALL,
    EXTRA_PLANE_EDIT_NAME,
    EXTRA_PLANE_EDIT_COMPANY,
    EXTRA_PLANE_EDIT_NUMBER,
    EXTRA_PLANE_EDIT_SEATS,
    NEW
}
